### PR TITLE
Fix endpoint issues for gh enterprise, closes #6

### LINKED ISSUE #6: Support for Github Enterprise API
I want to be able to use [Github Enterprise API endpoints](https://developer.github.com/v3/enterprise/) like this `http(s)://hostname/api/v3/`. Currently, my way of doing it is something like so: in `lib/index.js`, do:
`uri = this.opts.endpoint + method;` instead of `uri = url.resolve(this.opts.endpoint, method);`
Essentially, the `/api/v3` gets thrown away by the `url.resolve`.

### PR DESCRIPTION
**Pull request by taylorc93**
Using `url.resolve` drops the required `/api/<version>` in the endpoint for github enterprise.  This should fix that issue.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -105,8 +106,14 @@ GitHub.prototype.request = function(httpMethod, method, params, opts) {
 
     httpMethod = httpMethod.toUpperCase();
 
-    // Build url
-    uri = url.resolve(this.opts.endpoint, method);
+    // Build url, don't use url.resolve() for github enterprise endpoints:
+    // https://nodejs.org/api/url.html#url_url_resolve_from_to
+    // https://developer.github.com/v3/enterprise/#endpoint-urls
+    if (this.opts.endpoint === DEFAULT_GITHUB_ENDPOINT) {
```
Comment (SamyPesse) [inline lib/index.js]: Can you use something like [`urljoin`](https://www.npmjs.com/package/urljoin) instead to avoid the condition ?

Here is a code example: https://runkit.com/5845cf2fe3579b001497bbae/5845cf2fe3579b001497bbaf

**Review by SamyPesse — CHANGES_REQUESTED** [review]
Thanks!

File: lib/index.js (hunk 1 above)
Comment (SamyPesse) [reply lib/index.js]: Or [`urljoin.js`](https://github.com/GitbookIO/urljoin.js)

**Comment by taylorc93** [comment]
@SamyPesse Good call! Updated it.  Looks like using `npm i --save url-join` rewrote the `package.json`.  Bit annoying, but should still work

**Comment by SamyPesse** [comment]
Thanks awesome, merging and publishing a new version.

**Comment by SamyPesse** [comment]
Published as `0.11.1`,  Im a bit worried because I haven't tested it, but I should take time someday to add basic unit tests (like testing url resolution) and fix unit tests on travis.
